#!/usr/bin/env bash

CC=${CC:-}

RE2C_BIN=${RE2C_BIN:-`command -v re2c 2>/dev/null || true`}
GCC_BIN=`command -v gcc 2>/dev/null || true`
CLANG_BIN=`command -v clang 2>/dev/null || true`

if [ x"$RE2C_BIN" = x ]; then
    echo -e "error: re2c is not available please install re2c: http://re2c.org/"
	  exit 2
fi

if [ x"$CC" == x ]; then
    if [ x"$GCC_BIN" != x ]; then
        CC="gcc"
    else
        if [ x"$CLANG_BIN" != x ]; then
            CC="clang"
        fi
    fi
fi

if [ x"$CC" == x ]; then
    echo -e "error: unable to locate the compiler"
    exit 1
fi

export CFLAGS="-g -O0 -Wall -Werror"

if [ x"$CC" == xclang ]; then
    export CFLAGS="${CFLAGS} -fcolor-diagnostics"
fi

cd ./src

rm -f *.o *.out *.lo *.loT lemon scanner.c zephir.c
rm -rf .libs

echo -e "Generating scanner..."
${RE2C_BIN} -W --output scanner.c scanner.re

echo -e "Generating parser..."
${CC} -w lemon.c -o lemon
./lemon -l -s zephir.lemon

cat base.c >> zephir.c

${CC} -Wall -fPIC -c zephir.c scanner.c ${LDFLAGS}
${CC} -shared -o libzephir.so zephir.o
