#!/bin/sh
#
# Zephir Library
# Copyright (c) 2013-2018 Zephir Team (https://zephir-lang.com/)
#
# This source file is subject the MIT license, that is bundled with this
# package in the file LICENSE, and is available through the world-wide-web
# at the following url: https://zephir-lang.com/license.html               |

if test -z "$RE2C_VERSION"; then
    echo "The RE2C_VERSION variable is not set. Stop."
    exit 1
fi

if test "${RE2C_VERSION}" = "system"; then
    echo "Use system re2c. Skip."
    exit 0
fi

pkgname=re2c
source="https://github.com/skvadrik/${pkgname}/releases/download/${RE2C_VERSION}/${pkgname}-${RE2C_VERSION}.tar.gz"
downloaddir="${HOME}/.cache/${pkgname}/${pkgname}-${RE2C_VERSION}"
prefix="${HOME}/.local/opt/${pkgname}/${pkgname}-${RE2C_VERSION}"
bindir="${prefix}/bin"

if test ! -f "${bindir}/re2c"; then
	if test ! -d `dirname ${downloaddir}`; then
		mkdir -p `dirname ${downloaddir}`
	fi

	cd `dirname ${downloaddir}`

	if test ! -f "${pkgname}-${RE2C_VERSION}.tar.gz"; then
		curl -sSL "$source" -o "${pkgname}-${RE2C_VERSION}.tar.gz"
	fi

	if test ! -f "${pkgname}-${RE2C_VERSION}.tar.gz"; then
		echo "Unable to locate ${pkgname}-${RE2C_VERSION}.tar.gz file. Stop."
		exit 1
	fi

	if test ! -d "${downloaddir}"; then
		mkdir -p "${downloaddir}"
		tar -zxf "${pkgname}-${RE2C_VERSION}.tar.gz"
	fi

	if test ! -d "${downloaddir}"; then
		echo "Unable to locate re2c source. Stop."
		exit 1
	fi

	if test ! -d "${prefix}"; then
		mkdir -p "${prefix}"
	fi

	cd "${downloaddir}"
	./configure --prefix="${prefix}"

	make -j"$(getconf _NPROCESSORS_ONLN)"
	make install
fi

if test ! -x "${bindir}/re2c"; then
	echo "Unable to locate re2c executable. Stop."
	exit 1
fi

mkdir -p ${HOME}/bin
ln -s "${bindir}/re2c" ${HOME}/bin/re2c

${HOME}/bin/re2c --version
exit 0
