#define XX_INTERNAL                         1
#define XX_PUBLIC                           2
#define XX_PROTECTED                        3
#define XX_STATIC                           4
#define XX_PRIVATE                          5
#define XX_SCOPED                           6
#define XX_COMMA                            7
#define XX_REQUIRE                          8
#define XX_DOUBLEARROW                      9
#define XX_QUESTION                        10
#define XX_LIKELY                          11
#define XX_UNLIKELY                        12
#define XX_OR                              13
#define XX_AND                             14
#define XX_INSTANCEOF                      15
#define XX_BITWISE_OR                      16
#define XX_BITWISE_XOR                     17
#define XX_BITWISE_SHIFTLEFT               18
#define XX_BITWISE_SHIFTRIGHT              19
#define XX_EQUALS                          20
#define XX_IDENTICAL                       21
#define XX_LESS                            22
#define XX_GREATER                         23
#define XX_LESSEQUAL                       24
#define XX_GREATEREQUAL                    25
#define XX_NOTIDENTICAL                    26
#define XX_NOTEQUALS                       27
#define XX_ADD                             28
#define XX_SUB                             29
#define XX_CONCAT                          30
#define XX_MUL                             31
#define XX_DIV                             32
#define XX_MOD                             33
#define XX_ISSET                           34
#define XX_FETCH                           35
#define XX_EMPTY                           36
#define XX_INCLUSIVE_RANGE                 37
#define XX_EXCLUSIVE_RANGE                 38
#define XX_TYPEOF                          39
#define XX_CLONE                           40
#define XX_NEW                             41
#define XX_NOT                             42
#define XX_BITWISE_NOT                     43
#define XX_BITWISE_AND                     44
#define XX_PARENTHESES_CLOSE               45
#define XX_SBRACKET_OPEN                   46
#define XX_ARROW                           47
#define XX_NAMESPACE                       48
#define XX_IDENTIFIER                      49
#define XX_DOTCOMMA                        50
